# Generated by Django 6.0.4 on 2026-04-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
