# Generated by Django 6.0.4 on 2026-04-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_patientmodel_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='gen',
            new_name='gender',
        ),
    ]
