# Generated by Django 6.0.3 on 2026-04-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
